apiVersion: v1
Kind: PersistentVolumeClaim
metadata:
  name: mysql-dados
spec:
  accessModes:
    -ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo

--
apiVersion: apps/v1
Kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app:mysql
    template:
      metadata:
        labels:
          app:mysql
      spec:
        containers:
        - image: brennocm/projeto-database:1.0
          args:
          - "--ignore-db-dir=lost+found"
          imagePullPolicy: Always
          name: mysql
          ports:
          - containerPort: 3306
            name: mysql

            volumeMounts:
            - name: mysql-dados
              mounthPath: /var/lib/mysql/
          volumes:
          - name: mysql-dados
            persistentVolumeClaim:
              clainName: mysql-dados
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 6
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: brennocm/projeto-backend:1.0
        imagePullpolicy: Always
        ports:
        - containerPort: 80
